const CREATE_COURSE = "CREATE_COURSE"
const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"
const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS"
const BEGIN_API_CALL = "BEGIN_API_CALL"
const API_CALL_ERROR = "API_CALL_ERROR"



export { 
CREATE_COURSE, 
LOAD_COURSES_SUCCESS, 
LOAD_AUTHORS_SUCCESS, 
CREATE_COURSE_SUCCESS, 
UPDATE_COURSE_SUCCESS,
BEGIN_API_CALL,
API_CALL_ERROR
}